export const CategoryData = [
  {
    id: 1,
    name: 'Luqman',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 2,
    name: 'Wakeelan',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS42KAOVpagV38Fa_darcqWy4pUCkCxPGIDqA&usqp=CAU',
  },
  {
    id: 3,
    name: 'Naseera',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmi8PY5OoswVJ--xRdFM3GnfC9xqVqJWzPjA&usqp=CAU',
  },
  {
    id: 4,
    name: 'Munawar Hussain',
    ImageUrl:
      'https://thumbs.dreamstime.com/b/high-school-student-29699566.jpg',
  },
  {
    id: 5,
    name: 'junaid Ahmed',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 6,
    name: 'Dua',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 7,
    name: 'Wakeel Ahmed',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 8,
    name: 'Jamshed Ahmed',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 9,
    name: 'Muhammad Ishaq',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 10,
    name: 'Anita',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 11,
    name: 'Ali Akber',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 12,
    name: 'Zohaib Ahmed',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 13,
    name: 'Ghulam Sarwar',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 14,
    name: 'Alah Dino',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 15,
    name: 'Mohsin',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 16,
    name: 'Ghulam Mustafa',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 17,
    name: 'Muhammad haroon',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 18,
    name: 'Sajida',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 19,
    name: 'Ayesha',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 20,
    name: 'Naveedan',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
  {
    id: 21,
    name: 'Jihad Ahmed',
    ImageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ89eHUeqOyDzDqwKxV2R9LA5DYowjIZGzmkA&usqp=CAU',
  },
];
export const StudentDetails = [
  {
    id: 'p1',
    catId: 1,
    name: 'Luqman',
    fatherName: 'fatehi Ali',
    Class: 'Nazrah',
    StudentCode: '76',
    RegistrationNo: '141',
    AdmissionDate: '25/12/18',
    Code: '3100',
    Attendance: '24',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p2',
    catId: 2,
    name: 'Wakeelan',
    fatherName: 'Shah Nawaz',
    Class: 'Nazrah',
    StudentCode: '83',
    RegistrationNo: '147',
    AdmissionDate: '29/5/1',
    Code: '3100',
    Attendance: '19',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p3',
    catId: 3,
    name: 'Naseera',
    fatherName: 'kareem Bux',
    Class: 'Nazrah',
    StudentCode: '85',
    RegistrationNo: '148',
    AdmissionDate: '29/5/19',
    Code: '3100',
    Attendance: '19',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p4',
    catId: 4,
    name: 'Munawar Hussain',
    fatherName: 'Khalid Hussain',
    Class: 'Nazrah',
    StudentCode: '87',
    RegistrationNo: '150',
    AdmissionDate: '23/9/19',
    Code: '3100',
    Attendance: '19',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p5',
    catId: 5,
    name: 'junaid Ahmed',
    fatherName: 'Zulfiqar',
    Class: 'Nazrah',
    StudentCode: '92',
    RegistrationNo: '149',
    AdmissionDate: '23/9/19',
    Code: '3100',
    Attendance: '24',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p6',
    catId: 6,
    name: 'Dua',
    fatherName: 'Muhaamad urs',
    Class: 'Nazrah',
    StudentCode: '94',
    RegistrationNo: '154',
    AdmissionDate: '26/1/20',
    Code: '3100',
    Attendance: '19',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p7',
    catId: 7,
    name: 'Wakeel Ahmed',
    fatherName: 'Muhammad Ismail',
    Class: 'Nazrah',
    StudentCode: '95',
    RegistrationNo: '156',
    AdmissionDate: '6/6/21',
    Code: '3100',
    Attendance: '20',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p8',
    catId: 8,
    name: 'Jamshed Ahmed',
    fatherName: 'Zulfiqar',
    Class: 'Nazrah',
    StudentCode: '93',
    RegistrationNo: '155',
    AdmissionDate: '25/12/18',
    Code: '3100',
    Attendance: '0',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p9',
    catId: 9,
    name: 'Muhammad Ishaq',
    fatherName: 'Ali Anwar',
    Class: 'Nazrah',
    StudentCode: '96',
    RegistrationNo: '157',
    AdmissionDate: '6/6/21',
    Code: '3100',
    Attendance: '20',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p10',
    catId: 10,
    name: 'Anita',
    fatherName: 'Muhammad Ismail',
    Class: 'Nazrah',
    StudentCode: '99',
    RegistrationNo: '161',
    AdmissionDate: '15/8/21',
    Code: '3100',
    Attendance: '24',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p11',
    catId: 11,
    name: 'Ali Akber',
    fatherName: 'Muhammd Hashim',
    Class: 'Nazrah',
    StudentCode: '101',
    RegistrationNo: '159',
    AdmissionDate: '15/8/21',
    Code: '3100',
    Attendance: '24',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p12',
    catId: 12,
    name: 'Zohaib Ahmed',
    fatherName: 'Kareem Bux',
    Class: 'Nazrah',
    StudentCode: '102',
    RegistrationNo: '158',
    AdmissionDate: '15/8/21',
    Code: '3100',
    Attendance: '19',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p13',
    catId: 13,
    name: 'Ghulam Sarwar',
    fatherName: 'Khalid Hussain',
    Class: 'Nazrah',
    StudentCode: '103',
    RegistrationNo: '160',
    AdmissionDate: '15/8/21',
    Code: '3100',
    Attendance: '24',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p14',
    catId: 14,
    name: 'Alah Dino',
    fatherName: 'Arib Khan',
    Class: 'Nazrah',
    StudentCode: '104',
    RegistrationNo: '168',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '24',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p15',
    catId: 15,
    name: 'Mohsin',
    fatherName: 'Ali Asghar',
    Class: 'Nazrah',
    StudentCode: '105',
    RegistrationNo: '169',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '19',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p16',
    catId: 16,
    name: 'Ghulam Mustafa',
    fatherName: 'Gulam Ali',
    Class: 'Nazrah',
    StudentCode: '106',
    RegistrationNo: '167',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '24',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p17',
    catId: 17,
    name: 'Muhammad haroon',
    fatherName: 'khadim Hussain',
    Class: 'Nazrah',
    StudentCode: '107',
    RegistrationNo: '166',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '20',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p18',
    catId: 18,
    name: 'Sajida',
    fatherName: 'Wazeer Ali Dero',
    Class: 'Nazrah',
    StudentCode: '108',
    RegistrationNo: '164',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '20',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p19',
    catId: 19,
    name: 'Ayesha',
    fatherName: 'Khadim Hussain',
    Class: 'Nazrah',
    StudentCode: '109',
    RegistrationNo: '165',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '20',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },

  {
    id: 'p20',
    catId: 20,
    name: 'Naveedan',
    fatherName: 'Abdul Majeed',
    Class: 'Nazrah',
    StudentCode: '110',
    RegistrationNo: '163',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '19',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p21',
    catId: 21,
    name: 'Jihad Ahmed',
    fatherName: 'Zulfiqar',
    Class: 'Nazrah',
    StudentCode: '111',
    RegistrationNo: '170',
    AdmissionDate: '17/11/21',
    Code: '3100',
    Attendance: '5',
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
];
export const Detail = [
  {
    id: 'p1',
    name: 'Luqman',
    CatId: 1,
    deeniyat: 8,
    manzil: 28,
    sabki: 28,
    tajveed: 18,
    qawaid: 8,
    remarks: 'Weak',
    totalMarks: 90,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p2',
    name: 'Wakeelan',
    CatId: 2,
    deeniyat: 26,
    manzil: 26,
    sabki: 16,
    tajveed: 16,
    qawaid: 6,
    remarks: 'Normal',
    totalMarks: 80,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p3',
    name: 'Naseera',
    CatId: 3,
    deeniyat: 5,
    manzil: 25,
    sabki: 25,
    tajveed: 15,
    qawaid: 6,
    remarks: 'Good',
    totalMarks: 76,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p4',
    name: 'Munawar Hussain',
    CatId: 4,
    deeniyat: 10,
    manzil: 30,
    sabki: 30,
    tajveed: 20,
    qawaid: 10,
    remarks: 'Good',
    totalMarks: 90,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p5',
    name: 'junaid Ahmed',
    CatId: 5,
    deeniyat: 8,
    manzil: 26,
    sabki: 26,
    tajveed: 16,
    qawaid: 8,
    remarks: 'Nice',
    totalMarks: 84,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p6',
    name: 'Due',
    CatId: 6,
    deeniyat: 10,
    manzil: 30,
    sabki: 30,
    tajveed: 20,
    qawaid: 10,
    remarks: 'Good',
    totalMarks: 100,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p7',
    name: 'Waleed Ahmed',
    CatId: 7,
    deeniyat: 6,
    manzil: 26,
    sabki: 26,
    tajveed: 16,
    qawaid: 6,
    remarks: 'Good',
    totalMarks: 80,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p8',
    name: 'Jamshed Ahmed',
    CatId: 8,
    deeniyat: 0,
    manzil: 0,
    sabki: 0,
    tajveed: 0,
    qawaid: 0,
    remarks: 'Weak',
    totalMarks: 0,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p9',
    name: 'Muhammad Ishaq',
    CatId: 9,
    deeniyat: 6,
    manzil: 24,
    sabki: 22,
    tajveed: 12,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 70,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p10',
    name: 'Anita',
    CatId: 10,
    deeniyat: 6,
    manzil: 24,
    sabki: 24,
    tajveed: 12,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 72,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p11',
    name: 'Ali Akber',
    CatId: 11,
    deeniyat: 6,
    manzil: 24,
    sabki: 22,
    tajveed: 12,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 70,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p12',
    name: 'Zohaib Ahmed',
    CatId: 12,
    deeniyat: 6,
    manzil: 26,
    sabki: 26,
    tajveed: 16,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 80,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
    description:
      "The passage experienced a surge in popularity during the 1960s when Letraset used it on their dry-transfer sheets, and again during the 90s as desktop publishers bundled the text with their software. Today it's seen all around the web; on templates, websites, and stock designs. Use our generator to get your own, or read on for the authoritative history of lorem ipsum.",
  },
  {
    id: 'p13',
    name: 'Ghulam Sarver',
    CatId: 13,
    deeniyat: 6,
    manzil: 22,
    sabki: 22,
    tajveed: 16,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 68,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
    description:
      "The passage experienced a surge in popularity during the 1960s when Letraset used it on their dry-transfer sheets, and again during the 90s as desktop publishers bundled the text with their software. Today it's seen all around the web; on templates, websites, and stock designs. Use our generator to get your own, or read on for the authoritative history of lorem ipsum.",
  },
  {
    id: 'p14',
    name: 'Alah Dino',
    CatId: 14,
    deeniyat: 6,
    manzil: 26,
    sabki: 26,
    tajveed: 16,
    qawaid: 6,
    remarks: 'Good',
    totalMarks: 80,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
    description:
      "The passage experienced a surge in popularity during the 1960s when Letraset used it on their dry-transfer sheets, and again during the 90s as desktop publishers bundled the text with their software. Today it's seen all around the web; on templates, websites, and stock designs. Use our generator to get your own, or read on for the authoritative history of lorem ipsum.",
  },
  {
    id: 'p15',
    name: 'Mohsin',
    CatId: 15,
    deeniyat: 6,
    manzil: 22,
    sabki: 22,
    tajveed: 12,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 80,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p16',
    name: 'JGhulam Mustafa',
    CatId: 16,
    deeniyat: 6,
    manzil: 25,
    sabki: 25,
    tajveed: 15,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 77,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p17',
    name: 'Muhammad Haroon',
    CatId: 17,
    deeniyat: 6,
    manzil: 22,
    sabki: 22,
    tajveed: 12,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 68,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p18',
    name: 'Sajida',
    CatId: 18,
    deeniyat: 6,
    manzil: 26,
    sabki: 26,
    tajveed: 16,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 80,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p19',
    name: 'Ayesha',
    CatId: 19,
    deeniyat: 6,
    manzil: 22,
    sabki: 22,
    tajveed: 12,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 80,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p20',
    name: 'Naveedan',
    CatId: 20,
    deeniyat: 6,
    manzil: 24,
    sabki: 24,
    tajveed: 16,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 76,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
  {
    id: 'p21',
    name: 'Jihad Ahmed',
    CatId: 21,
    deeniyat: 5,
    manzil: 20,
    sabki: 20,
    tajveed: 10,
    qawaid: 6,
    remarks: 'Weak',
    totalMarks: 61,
    ImageUrl:
      'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2802609.jpg',
  },
];
